src/components/dropdown/dropdown-item.js
src/components/dropdown/dropdown.js
src/settings.js

Follows from https://github.ibm.com/ASUDOH/carbon-custom-elements/pull/1

feat(dropdown): add a11y interactions

---

package.json
src/components/dropdown/dropdown-story.ts
src/components/dropdown/dropdown.ts
src/components/modal/modal-story.ts
src/components/modal/modal.ts
src/components/tooltip/tooltip.ts
src/index-with-polyfills.ts
src/typings/vendor.d.ts

Fix misc TypeScript problems. Also run check with TSC in CI.

chore(components): clean-up TypeScript annotations

---

src/coding-conventions.md

Virtually everything in the `.md` file has been changed. Using "View file" in the dotted button would be the easiest for review. @cal-smith Please don't hesitate to ping me if you have any questions. Thanks!

docs(contributors): update coding conventions

---

plans/i0.md

Refs carbon-design-system/issue-tracking#121. To outline what to do in the remaining prototype phase (June). Feel free to suggest any ideas to add/rectify!

chore(planning): i0 plan

---

README.md

Please don't hesitate to bring up any suggestions!

docs(readme): introduce README

---

src/coding-conventions.md

Wrt mix-in, i18n and null checking.

docs(coding-convention): a few updates

---

src/components/button/button.ts
src/components/dropdown/dropdown.ts
src/components/modal/modal.ts

For event listeners called from lit-html template.
Fixes #23.

chore(components): method over field

---

plans/i1.md
plans/i2.md

Please don't hesitate to speak up if anybody have higher-priority items in your mind - Thanks!

docs(project): i1 and i2 plans

---

src/coding-conventions.md
src/ie-broken-selectors.md
src/index.ts

This adds some notes wrt ShadyCSS considerations, and some naming rules of component options.

docs(contributors): coding convention update

---

.storybook/config.ts
.storybook/theme.js
.storybook/webpack.config.js

This change is a little tweak of our Storybook UI to link back to our GitHub repo.

chore(devenv): link back go GH repo

---

tests/spec/button_spec.ts

test(button): add test for button

---

tests/spec/dropdown_spec.ts
tsconfig.json

This change allows test spec code to be typechecked (back).

chore(lint): typecheck test specs

---

src/components/dropdown/dropdown.ts
src/components/multi-select/README.md
src/components/multi-select/multi-select-item.ts
src/components/multi-select/multi-select-story.ts
src/components/multi-select/multi-select.scss
src/components/multi-select/multi-select.ts
src/globals/internal/collection-helpers.ts

Fixes #45.
Please refer to https://github.com/asudoh/carbon-custom-elements/blob/909e4d5b5ed6b757c4f47e5e26c04c0b437c2794/src/components/multi-select/README.md to see how it works.

feat(multi-select): introduce multi select

---

src/components/checkbox/checkbox-story.ts
src/components/checkbox/checkbox.ts
src/components/tile/clickable-tile.ts
src/components/tile/selectable-tile.ts
src/components/tile/tile-story.ts
src/components/tile/tile.scss
src/components/tile/tile.ts

This change also modified checkbox code to align with tile code.

feat(tile): introduce tile

---

README.md

docs(readme): add Angular/React live demo links

---

.storybook/angular/webpack.config.js
.storybook/webpack.config.js
package.json
src/components/checkbox/checkbox-story-angular.ts
src/components/data-table/data-table-story-angular.ts
src/components/loading/loading-story-angular.ts
src/components/modal/modal-story-angular.ts
src/components/multi-select/multi-select-story-angular.ts
src/components/notification/inline-notification.ts
src/components/notification/notification-story-angular.ts
src/components/overflow-menu/overflow-menu-story-angular.ts
src/components/structured-list/structured-list-story-angular.ts
src/components/tile/tile-story-angular.ts
src/components/tooltip/tooltip-story-angular.ts
src/components/ui-shell/side-nav.ts
src/components/ui-shell/ui-shell-story-angular.ts
tests/karma-test-shim.js
yarn.lock

This change adds stories of remaining components for Angular.
Refs #60.
@cal-smith The data table story has an example Angular component, not sure if it's a good Angular code, please feel free to point out (or change them later) any Angular problems. Thanks!

chore(devenv): add more Angular stories

---

.storybook/vue/addons.js
.storybook/vue/config.ts
.storybook/vue/create-vue-bindings-from-props.ts
.storybook/vue/manager-head.html
.storybook/vue/presets.js
.storybook/vue/theme.js
.storybook/vue/webpack.config.js
.storybook/webpack.config.js
README.md
package.json
src/components/button/button-story-vue.ts
src/components/dropdown/dropdown-story-vue.ts
tests/karma-test-shim.js
yarn.lock

Starting with button and dropdown. The Vue Storybook can be run by `yarn storybook:vue`.
Will set up `carbon-custom-elements-vue.netlify.com` once this PR is merged.
Refs #88.
@lee-chase Not sure if I follow Vue Storybook best practices well, but please don't hesitate to let me know if you think of any improvements. Thanks!

chore(devenv): introduce Vue stories

---

src/components/search/search-story-angular.ts
src/components/search/search-story-react.tsx
src/components/search/search-story-vue.ts
src/components/search/search-story.ts
src/components/search/search.scss
src/components/search/search.ts

feat(search): introduce search box

---

src/components/checkbox/checkbox-story-vue.ts
src/components/combo-box/combo-box-story-vue.ts
src/components/loading/loading-story-vue.ts
src/components/modal/modal-story-vue.ts
src/components/multi-select/multi-select-story-vue.ts
src/components/notification/notification-story-vue.ts
src/components/overflow-menu/overflow-menu-story-vue.ts
src/components/structured-list/structured-list-story-vue.ts
src/components/tile/tile-story-vue.ts
src/components/tooltip/tooltip-story-vue.ts
src/components/ui-shell/ui-shell-story-vue.ts

chore(devenv): add more Vue stories

---

README.md

This change just adds one-line sales pitch. Hope it makes sense, but @cal-smith please don't hesitate to bring up if you think of any alternatives!

docs(readme): add sales pitch

---

gulp-tasks/build.js
src/index-with-polyfills.ts

chore(build): build polyfills as modules

---

src/components/data-table/data-table-story-react.tsx
src/components/pagination/pagination.ts

Please use "ignore whitespace" setting for reviewing. @emyarod Please don't hesitate to ping me if you have any questions. Thanks!

docs(data-table): add React story for pagination

---

examples/codesandbox/basic/index.html

This change alleviates FOUC that is sometimes seen in our basic CodeSandbox example.

chore(codesandbox): avoid FOUC

---

package.json

This changes adds `module` and `typings` fields in `package.json`.

chore(build): update main fields

---

.github/workflows/reviewdog.yml

This change introduces `reviewdog` that can create PR comments upon ESLint result.

chore(lint): introduce reviewdog

---

README.md

docs(readme): add more notes for React wrapper

---

src/components/accordion/accordion-story.ts
src/components/button/button-story.ts
src/components/checkbox/checkbox-story.ts
src/components/code-snippet/code-snippet-story.ts
src/components/combo-box/combo-box-story.ts
src/components/content-switcher/content-switcher-story.ts
src/components/copy-button/copy-button-story.ts
src/components/data-table/data-table-story.ts
src/components/date-picker/date-picker-story.ts
src/components/dropdown/dropdown-story.ts
src/components/inline-loading/inline-loading-story.ts
src/components/input/input-story.ts
src/components/loading/loading-story.ts
src/components/modal/modal-story.ts
src/components/multi-select/multi-select-story.ts
src/components/notification/notification-story.ts
src/components/overflow-menu/overflow-menu-story.ts
src/components/pagination/pageination-story.ts
src/components/progress-indicator/progress-indicator-story.ts
src/components/radio-button/radio-button-story.ts
src/components/search/search-story.ts
src/components/slider/slider-story.ts
src/components/structured-list/structured-list-story.ts
src/components/tabs/tabs-story.ts
src/components/tag/tag-story.ts
src/components/textarea/textarea-story.ts
src/components/tile/tile-story.ts
src/components/toggle/toggle-story.ts
src/components/tooltip/tooltip-story.ts
src/components/ui-shell/ui-shell-story.ts

This change applies ES optional chaining feature introduced in #168 to the story parameters coming from knobs introduced in #176.

chore(devenv): optional chaining to stories

---

package.json

chore(build): update package.json

---

src/components/accordion/accordion-story-react.tsx
src/components/button/button-story-react.tsx
src/components/checkbox/checkbox-story-react.tsx
src/components/code-snippet/code-snippet-story-react.tsx
src/components/combo-box/combo-box-story-react.tsx
src/components/content-switcher/content-switcher-story-react.tsx
src/components/copy-button/copy-button-story-react.tsx
src/components/data-table/data-table-story-react.tsx
src/components/date-picker/date-picker-story-react.tsx
src/components/dropdown/dropdown-story-react.tsx
src/components/input/input-story-react.tsx
src/components/loading/loading-story-react.tsx
src/components/modal/modal-story-react.tsx
src/components/multi-select/multi-select-story-react.tsx
src/components/notification/notification-story-react.tsx
src/components/overflow-menu/overflow-menu-story-react.tsx
src/components/progress-indicator/progress-indicator-story-react.tsx
src/components/radio-button/radio-button-story-react.tsx
src/components/search/search-story-react.tsx
src/components/slider/slider-story-react.tsx
src/components/structured-list/structured-list-story-react.tsx
src/components/tabs/tabs-story-react.tsx
src/components/textarea/textarea-story-react.tsx
src/components/tile/tile-story-react.tsx
src/components/toggle/toggle-story-react.tsx
src/components/tooltip/tooltip-story-react.tsx
src/components/ui-shell/ui-shell-story-react.tsx

docs: fix typo

---

.gitignore
gulpfile.js
package.json

chore(build): more work to ship Sass

---

.storybook/webpack.config.js
gulp-tasks/build.js

fix(build): use ESM for Babel helpers

---

.storybook/angular/config.ts
.storybook/config.ts
.storybook/react/config.tsx
.storybook/vue/config.ts
.storybook/webpack.config.js
gulp-tasks/build.js
package.json
yarn.lock

This change adds the following:
* A build generate `*.rtl.css.js`, which is a RTL version of `CSSResult` module
* An environment variable for our dev env (Storybook), `STORYBOOK_CARBON_CUSTOM_ELEMENTS_USE_RTL`, to demonstrate/test RTL there

chore(build): support RTL

---

src/components/skeleton-text/skeleton-text-story-angular.ts
src/components/skeleton-text/skeleton-text-story-react.tsx
src/components/skeleton-text/skeleton-text-story-vue.ts
src/components/skeleton-text/skeleton-text-story.ts
src/components/skeleton-text/skeleton-text.scss
src/components/skeleton-text/skeleton-text.ts

feat(skeleton-text): introduce skeleton text

---

src/components/skeleton-placeholder/skeleton-placeholder-story-angular.ts
src/components/skeleton-placeholder/skeleton-placeholder-story-react.tsx
src/components/skeleton-placeholder/skeleton-placeholder-story-vue.ts
src/components/skeleton-placeholder/skeleton-placeholder-story.ts
src/components/skeleton-placeholder/skeleton-placeholder.scss
src/components/skeleton-placeholder/skeleton-placeholder.ts

feat(skeleton-placeholder): skeleton placeholder

---

src/components/progress-indicator/progress-indicator.scss

fix(progress-indicator): fix imcomplete color

---

src/components/multi-select/multi-select-story.ts
src/components/multi-select/multi-select.ts
tests/snapshots/bx-multi-select.md
tests/spec/multi-select_spec.ts

Also fixes a bug found during the test, which is, specifying `value` attribute at initialization don't create a close button where it should.

test(multi-select): add tests

---

examples/codesandbox/angular/package.json
examples/codesandbox/basic/package.json
examples/codesandbox/form/angular/package.json
examples/codesandbox/form/basic/package.json
examples/codesandbox/form/redux-form/package.json
examples/codesandbox/ie/package.json
examples/codesandbox/react/package.json
examples/codesandbox/rtl/package.json
examples/codesandbox/styling/custom-style/package.json
examples/codesandbox/styling/theme-zoning/package.json
examples/codesandbox/vue/package.json

chore(examples): upgrade carbon-custom-elements

---

examples/codesandbox/angular/package.json
examples/codesandbox/basic/package.json
examples/codesandbox/form/angular/package.json
examples/codesandbox/form/basic/package.json
examples/codesandbox/form/redux-form/package.json
examples/codesandbox/ie/package.json
examples/codesandbox/react/package.json
examples/codesandbox/rtl/package.json
examples/codesandbox/styling/custom-style/package.json
examples/codesandbox/styling/theme-zoning/package.json
examples/codesandbox/vue/package.json

This change upgrades live examples to use the RC version of this library.

chore(examples): upgrade to RC

---

src/components/button/button.scss

Fixes #437.
Refs carbon-design-system/ibm-dotcom-library#3093。

fix(button): support text wrap

---

.kodiak.toml

This change sets up Kodiak for auto merge PRs.

chore(build): set up Kodiak

---

examples/codesandbox/angular/package.json
examples/codesandbox/basic/package.json
examples/codesandbox/form/angular/package.json
examples/codesandbox/form/basic/package.json
examples/codesandbox/form/redux-form/package.json
examples/codesandbox/ie/package.json
examples/codesandbox/react/package.json
examples/codesandbox/rtl/package.json
examples/codesandbox/styling/custom-style/package.json
examples/codesandbox/styling/theme-zoning/package.json
examples/codesandbox/vue/package.json
package.json
src/components/combo-box/combo-box.scss
src/components/combo-box/combo-box.ts
src/components/dropdown/dropdown.ts
src/components/tabs/tabs-story.scss
tests/snapshots/bx-combo-box.md
tests/snapshots/bx-dropdown.md
tests/snapshots/bx-multi-select.md
yarn.lock

(Requires #446 to pass the CI)

chore(dependencies): upgrade to Carbon 10.16

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/user_story.md
.github/PULL_REQUEST_TEMPLATE.md
.gitignore

This adds a number of issue templates as well a a PR template to the repo.
**New**
- Issue templates
- PR template

chore(github): adding templates to the repo

---

tools/babel-plugin-create-react-custom-element-type-def.js
tools/babel-plugin-create-react-custom-element-type.js

This change attempts to support custom element classes using mixins for react wrapper generation code.
**Changed**
- An attempt to support custom element classes using mixins for react wrapper generation code.

chore(react-wrapper): support mixins

---

src/components/button/button-story.ts
src/components/button/button.ts

Refs #523.
**New**
- Tertiary button variant.

feat(button): add tertiary variant

---

.github/workflows/automerge.yml

Adds a GitHhub action workflow to auto-merge release branch to `master` branch.
**New**
- A GitHhub action workflow to auto-merge release branch to `master` branch.

chore(build): add automerge workflow

---

src/components/link/link-story-angular.ts
src/components/link/link-story-react.tsx
src/components/link/link-story-vue.ts
src/components/link/link-story.ts
src/components/link/link.ts

#530 
Add size variants to `Link`
**New**
- size variants `sm` and `lg`

feat(link): add size variants

---

src/components/button/button-story.ts
src/components/button/button.ts

#526 
Adds extra large size variant
**New**
- `xl` size variant

feat(button): add XL size variant

---

.github/workflows/deploy.yml
manifest.yml

Refs #566.
Updates the deploy logic to have a new host for the Storybook site.
**Changed**
- Updates the deploy logic to have a new host for the Storybook site.

chore(build): update deploy logic

---

.github/workflows/deploy.yml
tools/deploy.sh

Refs #566.
**New**
- A logic to deploy to GH pages.

chore(build): add logic to deploy to GH pages

---

README.md
docs/welcome-story.mdx

**Removed**
- Stale README sentences.

docs(readme): misc update

---

src/components/pagination/pagination.scss
src/components/pagination/pagination.ts
tests/snapshots/bx-pagination.md

Refs #592.
Fixes Carbon core regression of responsive style of `<bx-pagination>`, by updating the markup to catch up with Carbon core change.
**Changed**
- Fixes Carbon core regression of responsive style of `<bx-pagination>`.

fix(pagination): fix responsive behavior

---

src/components/date-picker/date-picker-story-angular.ts
src/components/date-picker/date-picker-story-react.tsx
src/components/date-picker/date-picker-story-vue.ts
src/components/date-picker/date-picker-story.ts
src/components/date-picker/date-picker.ts
tests/spec/date-picker_spec.ts

Refs #584.
Adds event-based form participation feature to `<bx-date-picker>`. For the purpose, adds `disabled` and `name` attributes. The submitted value will be the date of the ISO8601 format.
**New**
- Event-based form participation feature to `<bx-date-picker>`.
- `disabled` and `name` attributes to `<bx-date-picker>`. The former is propagated to `<bx-date-picker-input>`.

feat(data-picker): support form participation

---

.storybook/angular/preview.ts
.storybook/angular/theme.ts
.storybook/preview.ts
.storybook/react/preview.tsx
.storybook/react/theme.ts
.storybook/theme.ts
.storybook/vue/preview.ts
.storybook/vue/theme.ts

Fixes a bug where the title of Storybook was not correctly shown. Also adds library version number to the title.
**Changed**
- Fixes a bug where the title of Storybook was not correctly shown.
- Adds library version number to the title.

chore(devenv): fix Storybook title

---

tools/deploy.sh

**Changed**
- Fixes bugs in deploy script to `web-components.carbondesignsystem.com`.

chore(ci): update deploy script

---

README.md
docs/welcome-story-angular.mdx
docs/welcome-story.mdx

**Changed**
- Updates `README.md` to reflect changes in `carbon-website` repo.

docs(readme): misc updates

---

README.md
docs/welcome-story.mdx

**Changed**
- Reflect latest update to Carbon website by @jeffchew  to our `README`.

docs(readme): another in sync with Carbon website

---

src/components/notification/inline-notification.scss
src/components/notification/inline-notification.ts
src/components/notification/notification-story-angular.ts
src/components/notification/notification-story-react.tsx
src/components/notification/notification-story-vue.ts
src/components/notification/notification-story.ts
src/components/notification/toast-notification.scss

#644 
Adds low contrast mode to the `notifications` component.
**New**
- `low-contrast` mode
**Changed**
- update Storybook stories

feat(notification): add low contrast mode

---

src/components/slider/slider.ts

#647
Updates the slider button position correctly when a minimum value other than 0 is given.
**Changed**
- subtracts `min` from overall value (thanks @asudoh!)

fix(slider): fixes out of range positioning

---

src/components/combo-box/combo-box-story.ts
src/components/combo-box/combo-box.ts

#651 
Ensure that when a user searches for an option that is out of view in the ComboBox, the selection will be scrolling into view.
**New**
- `scrollIntoView` when selected item is out of view

feat(combo-box): add scrolling to selected item on input

---

src/components/list/list-story.ts
src/components/list/ordered-list.ts
src/components/list/unordered-list.ts

#6185
add isExpressive prop to `ordered-list` & `unordered-list` to match Carbon
**New**
- isExpressive prop

feat(list): add isExpressive prop

---

src/components/button/button-story-angular.ts
src/components/button/button-story-react.tsx
src/components/button/button-story-vue.ts
src/components/button/button-story.ts
src/components/button/button.scss
src/components/button/button.ts

feat(button): add isExpressive prop

---

package.json

{{Provide url(s) to the related ticket(s) that this pull request addresses}}
Update version 
**Changed**
- version

chore(version): update to 1.14.0

---

package.json
src/components/link/link.ts

none
need to change _handleSlotChange to protected to use in Carbon for IBM.com library

fix(link): use protected & bump version

---

package.json

This will release `v1.16.0` of `carbon-web-components`.
**Changed**
- `package.json`

chore(release): bump version 1.16.0

---

.storybook/container.ts

Use `import type` from TypeScript.
**Changed**
- Use `import type` from TypeScript.

Use `import type` from TypeScript

---

src/components/data-table/table-header-cell.ts

{{Provide url(s) to the related ticket(s) that this pull request addresses}}
{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}
{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}
**New**
- {{new thing}}
**Changed**
- {{changed thing}}
**Removed**
- {{removed thing}}

docs(data-table): updating `sort-direction` docs

---

package.json

This will bump/trigger the 1.17.0 release.
**Changed**
- `package.json`

chore(release): bump to version 1.17.0

---

examples/codesandbox/angular/src/main.ts
examples/codesandbox/form/angular/src/app/app.component.ts
examples/codesandbox/form/angular/src/main.ts
tools/get-changelog.js

chore(eslint): disable lint warnings

---

.github/workflows/dependabot-yarn-mirror.yml

Fix checks to activate the action accordingly.

fix(ci): fix the yarn offline action

---

package.json
yarn.lock

Remove `lit-html` from resolutions.

chore(deps): remove lit-html from resolutions

---

.github/workflows/percy-update-base.yml
.github/workflows/publish.yml
.github/workflows/reviewdog.yml

chore(ci): update prevent actions

---

src/typings/jsx-elements.d.ts

Remove duplicated `bx-loading`

fix: remove duplicated `bx-loading`

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/question.yaml
.github/workflows/ci-check.yml
.github/workflows/percy-update-base.yml
.github/workflows/publish.yml
README.md
docs/form-story-angular.mdx
docs/form-story-react.mdx
docs/form-story.mdx
docs/form.md
docs/styling-story.mdx
docs/styling.md
docs/welcome-story-angular.mdx
docs/welcome-story-react.mdx
docs/welcome-story.mdx
examples/codesandbox/styling/theme-zoning/index.html
tools/deploy.sh

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5230
This updates all references of `master` branch to `main`.
**Changed**
- Multiple files updated to reference `main`

chore(branch): rename branch to `main`

---

src/components/search/search.ts

#243 
Adds form data event handling.
**New**
- `formData` event handling added to `search` component

feat(search): adds `formdata` event handling

---

examples/codesandbox/next/components/BXDropdownDemo.module.css
renovate.json

Disable Renovate (for real this time). Also replace `gstatic` references to use IBM Akamai server instead.
**Changed**
- disable `renovate`
- change `gstatic` Plex references to Akamai

chore(renovate): disable renovate for real this time
