carbon-design-system/carbon-web-components

src/components/modal/modal.ts, src/components/tooltip/tooltip.ts, src/globals/decorators/HostListener.ts, src/globals/mixins/HostListener.ts, src/typings/constructor.d.ts
`@HostListener(type, options?)` decorator attaches an event listener of the host element of a custom element.
The custom element class using `@HostListener()` has to extend `HostListenerMixin` that does the actual event listener work. Otherwise, `@HostListener()` throws an error.
=> chore(components): introduce @HostListener

src/components/structured-list/structured-list-body.ts, src/components/structured-list/structured-list-head.ts, src/components/structured-list/structured-list-header-row.ts, src/components/structured-list/structured-list-row.ts, src/components/structured-list/structured-list-story.ts, src/components/structured-list/structured-list.scss, src/components/structured-list/structured-list.ts, src/globals/internal/radio-group-manager.ts
Introduces `<bx-structured-list>`, etc. - Carbon structured list. With experimental keyboard navigation support for selection.
=> feat(structured-list): add bx-structured-list

src/globals/mixins/HostListener.ts, src/typings/vendor.d.ts
This change makes `@HostListener('focus')` capture descendant nodes' (e.g. ones' in shadow DOM) focus events. Similar for `blur` as well.
=> feat(host-listener): supports delegated focus/blur

src/components/floating-menu/floating-menu.ts
This change fixes the issue where floating menu is placed at a wrong position when floating menu is put in an element whose `left`/`top` positions of its `getBoundingClientReact()` are non-zero or such element has `position:static`.
=> fix(floating-menu): take container's position

.storybook/components/focus-trap/focus-trap.scss, .storybook/components/focus-trap/focus-trap.ts, .storybook/config.ts, package.json, src/components/dropdown/dropdown.ts, src/components/modal/modal-close-button.ts, src/components/modal/modal.ts, src/components/overflow-menu/overflow-menu.ts, src/components/structured-list/structured-list.ts, src/globals/settings.ts, yarn.lock
This change does the following:
- Attempts to focus on the element in the following priority order, when modal gets open:
- An element that application specifies via `data-modal-primary-focus` attribute
- A primary button
- The first focusable element in modal or modal itself
- Attempts to focus on the first focusable element in modal (or modal itself), when modal body loses focus, and the latest focused element follows the modal body in DOM order
- Attempts to focus on the last focusable element in modal (or modal itself), when modal body loses focus, and the latest focused element precedes the modal body in DOM order
This change also:
- Adds the selector for tabbable elements (borrowed from @cal-smith's #2), adding our custom elements that should be focusable
- Enhances the example …
=> feat(modal): introduce focus-wrap

src/components/dropdown/dropdown.ts, tests/spec/dropdown_spec.ts
Given the ID-ref is in shadow DOM, we don't need to generate unique ID for that.
=> chore(dropdown): make ID-ref simpler

.storybook/_container.scss, .storybook/components/focus-trap/focus-trap.scss, .storybook/components/focus-trap/focus-trap.ts, .storybook/config.ts
This change introduces a new prefix for custom element name as well as for BEM, `bx-ce-demo`, used only for our dev env. Doing so allows us to distinguish prefix for dev env from one for BEM prefix used only for `carbon-custom-elements`.
=> chore(devenv): introduce prefix for devenv

.storybook/webpack.config.js
This change is for allowing type annotations in our `story.ts` code.
=> chore(devenv): allow type annotation in story code

src/components/dropdown/dropdown.ts, src/components/modal/modal.ts
Doing so allows our custom events to bubble up and to go through shadow DOM boundary, useful when our components are used in shadow DOM.
=> chore(components): make custom events composed

src/components/data-table/README.md, src/components/data-table/_table-core.scss, src/components/data-table/_table-selection.scss, src/components/data-table/_table-sizes.scss, src/components/data-table/_table-sort.scss, src/components/data-table/core-library-style-questions.md, src/components/data-table/data-table-story.ts, src/components/data-table/data-table.scss, src/components/data-table/data-table.ts, src/components/data-table/stories/data.ts, src/components/data-table/stories/types.ts, src/components/data-table/table-body.ts, src/components/data-table/table-cell.ts, src/components/data-table/table-head.ts, src/components/data-table/table-header-cell.ts, src/components/data-table/table-header-row.ts, src/components/data-table/table-row.ts, src/components/data-table/table.ts, src/components/structured-list/structured-list-row.ts
This change re-implements `carbon-components` style code temporarily for now, from the following reasons:
* Many of the style rules are not supported by Sass `@extend`
* There are some open questions in `carbon-components` style code, and fiddling with an alternate implementation may help solving those questions
Please see https://github.com/asudoh/carbon-custom-elements/blob/75cb84052984644ab4ad0bd0910982c5e6a8f686/src/components/data-table/README.md for the basic notion of how the data table in `carbon-custom-elements` is implemented. Please don't hesitate to bring up if there are any questions. Thanks!
=> feat(data-table): introduce data table

src/components/implementation-practice.md
This change adds `implementation-practice.md`, which gives contributors some food for thoughts on implementing some simple components.
=> docs(contributors): component implementation guide

.storybook/addon-carbon-theme/components/Panel.js
This change fixes theme switcher selection being reset when user clicks on another Storybook add-on tab and then goes back to Carbon theme add-on tab.
=> chore(devenv): fix theme switcher being reset

.storybook/webpack.config.js, src/polyfills/element-closest.js
This change fixes the following issues:
* JavaScript error when `Element.prototype.closest()` is called in shady DOM
* Non-transpiled `lit-html` code generated from `@carbon/icons`
=> fix(browser-support): misc IE fixes

src/components/modal/modal-close-button.ts, src/components/modal/modal.ts, tests/spec/.eslintrc, tests/spec/modal_spec.ts
This change does the following things:
* Escape key support to close modal
* Introduce `selectorCloseButton` configuration option, that maintains the list of close buttons
* A change not to fire `bx-modal-beingclosed`, etc. custom events if the modal is closed already
Also this change adds unit tests against modal.
Refs #50.
=> chore(modal): misc API updates

src/components/modal/modal.ts, src/globals/mixins/host-listener.ts
This changes adds the following features to `<bx-modal>`:
* Introduces focus-pop behavior
* Traps focus by itself, for its focus-wrap feature
This change also adds a feature to `@HostListener()` decorator to hook event listeners on shadow root, which is useful if we want to get events that are not re-targeted.
=> feat(modal): keyboard nav enhancements

src/coding-conventions.md, src/components/checkbox/checkbox.ts, src/components/data-table/data-table-story.ts, src/components/data-table/table-row.ts, src/components/modal/modal.ts, src/components/tile/selectable-tile.ts, src/components/ui-shell/header-menu-button.ts, src/components/ui-shell/header-menu.ts, src/components/ui-shell/side-nav-link.ts, src/components/ui-shell/side-nav-menu.ts
This change makes the usage of `private`/`protected` a bit more coherent across the codebase. This change also adds a guideline in that area.
=> chore(components): make API exposure consistent

.babelrc, .storybook/webpack.config.js, package.json, src/globals/decorators/host-listener.ts, tests/karma.conf.js, yarn.lock
`@HostListener` decorator used to support only with TS coolchain, which is based on legacy decorator spec. This change makes `@HostListener` decorator support one with latest Babel toolchain, which is based on newer decorator spec.
This change allows us to use one transpiler (Babel) to generator the transpiled code, instead of using two transpilers.
=> chore(build): remove TS toolchain from build

.storybook/webpack.config.js
This change fixes broken Storybook `addon-storysource` add-on in Angular/React environment.
Refs #60.
=> chore(devenv): fix Storysource for Angular/React

.gitignore, gulp-tasks/config.js, package.json
This change also ensures that the bundled build is part of the NPM package.
Refs #76.
=> chore(build): change bundle directory

src/polyfills/index.js
Our `lit-html` "spread" directive uses this API.
=> chore(build): add Object.is() to polyfills

src/components/pagination/pagination.ts, src/globals/internal/handle.ts, src/globals/mixins/host-listener.ts, src/globals/wrappers/createReactCustomElementType.ts, src/typings/vendor.d.ts, tests/utils/event-manager.ts
`Handle` used to be defined in `vendor.d.ts` given it originally comes from `carbon-components` library, but given `carbon-custom-elements` does not ship `vendor.d.ts` as of today it causes a TS compilation error due to missing `Handle` references from the `.d.ts` code in `carbon-custom-elements`.
Shipping `vendor.d.ts` was a possible option, but given `Handle` is the only interface that requires "re-export", defining `Handle` by our own made more sense for now.
=> chore(build): define Handle interface in src

src/coding-conventions.md, src/components/checkbox/checkbox.ts, src/components/pagination/page-sizes-select.ts, src/components/pagination/pagination.ts, src/components/search/search.ts
This change fixes an issue where an instance property of checkbox missed its `private` declaration. This change also aligns new code to existing code where non-API-purpose properties are `private` unless we expect in-house usage of inheritance.
=> chore(components): clean-up private/protected

src/components/checkbox/checkbox.ts, src/components/combo-box/combo-box.ts, src/components/dropdown/dropdown.ts, src/components/input/input.ts, src/components/multi-select/multi-select-item.ts, src/components/pagination/page-sizes-select.ts, src/components/pagination/pages-select.ts, src/components/search/search.ts, src/components/tile/expandable-tile.ts, src/components/tile/selectable-tile.ts, tests/snapshots/bx-checkbox.md
Given shadow DOM creates an isolated space for element IDs, we don't need unique ID generation logic for IDs used in shadow DOM.
=> chore(components): switch to fixed IDs

.storybook/webpack.config.js, gulp-tasks/build.js, package.json, yarn.lock
This is a follow-up work of #144, where there was remaining build code to be adjusted for Carbon 10.7. Such build code was originally introduced to support CSS custom properties (#122).
This change also makes sure that Sass build failure causes failure of the corresponding Gulp task, so CI fails.
=> chore(build): fix custom property build

src/components/button/button.ts, tests/snapshots/bx-btn.md, tests/spec/button_spec.ts
This change ensures `null`-checking string properties before setting them as attributes, ensuring that `null`/`undefined` won't be set as attribute value.
=> fix(button): null-check properties

src/components/input/input.ts
This change is to ensure `<bx-input>` supports programmatic change in `value`. This change is needed as after-creation attribute change in `<input>`'s `value` won't be reflected to the UI.
This change also removes `reflect: true` from `value` property to get in sync with native `<input>` as well as `<bx-checkbox>`.
=> fix(input): support programmatic change in value

src/components/textarea/textarea.ts, tests/snapshots/bx-textarea.md, tests/spec/textarea_spec.ts
This change ensures that `value` attribute of `<bx-textarea>` is reflected to the `<textarea>` in shadow DOM at initialization, where `lit-element` attempts to reflect `value` attribute to `value` property before it renders `<textarea>`.
=> fix(textarea): reflect value attribute on init

gulp-tasks/build.js, gulp-tasks/lint.js, gulpfile.js, package.json, src/directives-angular/checkbox.ts, src/directives-angular/index.ts, src/directives-angular/input.ts, src/directives-angular/slider.ts, src/typings/vendor.d.ts, tests/karma.conf.js, tests/polyfills/.eslintrc, tests/polyfills/angular.ts, tests/spec/checkbox-angular_spec.ts, tests/spec/input-angular_spec.ts, tests/spec/slider-angular_spec.ts, tsconfig-angular-esm2015.json, tsconfig-angular-esm5.json, yarn.lock
(Continuation of #156. Difference from the latest code of #156 is that this PR does APF support by using `ngc`, a primitive behind `ng-packagr`)
This change implements Angular directives that implement `ControlValueAccessor` interface for components that should be able to interact with `<form>` (e.g. `<bx-input>`), so `[(ngModel)]` works with those.
This change relies on automated test cases for testing and manual test case will be in a separate PR. You can take a glance at manual test case [here](https://github.com/asudoh/carbon-custom-elements/tree/form-examples/examples/codesandbox/form/angular), which can be run by the following:
```sh
> git fetch git@github.com:asudoh/carbon-custom-elements.git form-data
> git checkout FETCH_HEAD
> gulp clean
> gulp build
> git fetch …
```
=> feat(angular): introduce form directives

.eslintignore, package.json, src/components/input/input-story-react.tsx, src/components/textarea/textarea-story-react.tsx
This change ensures `.tsx` files, etc. are covered in `yarn lint:scripts` task and `lint-staged`.
=> chore(lint): add file extensions to cover

package.json, yarn.lock
This change upgrades `node-sass` to `4.12.x` or higher, that supports Node 12.
=> chore(dependencies): upgrade node-sass

gulp-tasks/build.js, gulp-tasks/clean.js, gulp-tasks/config.js, gulpfile.js
Shipping our Sass code allows users to create custom `.css.js` files, e.g. an optimized version that contains styles of all components application uses and making `styles` of each components point to such single `.css.js`. In this way duplicate styles can be eliminated by `import-once`.
=> chore(build): ship sass code

src/components/date-picker/date-picker-story-angular.ts, src/components/date-picker/date-picker-story-react.tsx, src/components/date-picker/date-picker-story-vue.ts, src/components/date-picker/date-picker-story.ts, src/components/date-picker/date-picker.ts
With this change, `<bx-date-picker>` emits `bx-date-picker-flatpickr-error` event when Flatpickr calls its error callback. With this event, application can detect if user commits a date with a wrong date format, etc.
=> feat(date-picker): propagate error from Flatpickr

src/components/checkbox/checkbox.ts, src/components/code-snippet/code-snippet.ts, src/components/pagination/page-sizes-select.ts, src/components/search/search.ts, src/components/toggle/toggle.ts, tests/snapshots/bx-checkbox.md, tests/snapshots/bx-code-snippet.md, tests/snapshots/bx-toggle.md
This change supports `<slot>`s corresponding to some text attributes where it makes sense.
=> chore(components): misc slot supports

src/components/content-switcher/content-switcher.ts, src/components/tabs/tabs.ts
This change introduces `selectorItemEnabled` configuration in content switcher and tabs, to get simpler logic for navigation considering disabled items.
=> chore(content-switcher): optimize navigation

examples/codesandbox/angular/browserslist, examples/codesandbox/custom-style/package.json, examples/codesandbox/react/package.json, gulp-tasks/build.js
This change updates `browserlist` configurations for ES2015+ compile target. Notably `ie_mob` is added for exclusion that caused ES5 transpilation in some environments (Parcel-based CodeSandbox examples).
=> chore(build): update browserlist

src/components/slider/slider.ts
This change ensures `<bx-slider>`'s `min`, `max`, `step` and `stepRatio` properties are kept as string, to better align with the APIs of `<input type="range">` as well as `<bx-number-input>`.
=> fix(slider): normalize properties to string

docs/styling.md, examples/codesandbox/rtl/.gitignore, examples/codesandbox/rtl/package.json, examples/codesandbox/rtl/sandbox.config.json, examples/codesandbox/rtl/src/index.ejs, examples/codesandbox/rtl/src/index.js, examples/codesandbox/rtl/webpack.config.js
Will get this PR out of draft once we cut a release with the series of RTL changes. This example can be run by the following for now:
1. Checkout #201
2. Cherry-pick #206 onto above
3. `yarn clean && yarn build`
4. Checkout this commit
5. `cd /path/to/carbon-custom-elements/examples/codesandbox/rtl`
6. `yarn install`
7. `cd node_modules/carbon-custom-elements`
8. `rm -Rf es`
9. `cp -r /path/to/carbon-custom-elements/es .`
10. `cd ../..`
11. `yarn start`
12. Open Chrome
12. Go to chrome://settings/?search=language and click on the Language section highlighted
14. Add a RTL language (e.g. Arabic) and move it to the top
15. Open localhost:8080
=> docs(rtl): add RTL example

babel-plugin-create-react-custom-element-type.js
This change to React wrapper Babel plugin makes it support setter-only declared properties or one whose setter is defined first.
Refs #230.
=> chore(build): support setter-only properties

src/components/date-picker/date-picker-input.ts, src/components/date-picker/date-picker-story-angular.ts, src/components/date-picker/date-picker-story-react.tsx, src/components/date-picker/date-picker-story-vue.ts, src/components/date-picker/date-picker-story.ts
This change adds `invalid` attribute to `<bx-date-picker-input>` to align to `<bx-input>`, etc.
=> fix(date-picker): support separate invalid prop

src/components/data-table/table.ts, src/components/floating-menu/floating-menu.ts, src/components/modal/modal.ts, src/components/tooltip/tooltip.ts, tests/spec/.eslintrc, tests/spec/modal_spec.ts, tests/spec/tooltip_spec.ts
Instead of change in attributes. Given we have several properties that are not reflected back to attributes and tracking changes only in attributes loses track of those properties.
=> chore(components): track change in properties

yarn.lock
This change updates `yarn.lock` to avoid `Cannot find module 'array-find-index'` error.
=> chore(dependencies): update yarn.lock

README.md, package.json
Moving some of `peerDependencies` to `dependencies` for misc dependencies. This reduces some workload when setting up an application using `carbon-custom-elements` library.
Fixes #224.
=> chore(dependencies): reduce peerDependencies

.prettierignore
Adds snapshots to `.prettierignore`, as they are auto-generated files.
=> chore(lint): add snapshots to .prettierignore

src/components/button/button-skeleton.ts, src/components/button/button-story-angular.ts, src/components/button/button-story-react.tsx, src/components/button/button-story-vue.ts, src/components/button/button-story.ts, src/components/button/button.ts, src/components/date-picker/date-picker-input.ts, src/components/date-picker/date-picker-story-angular.ts, src/components/date-picker/date-picker-story-react.tsx, src/components/date-picker/date-picker-story-vue.ts, src/components/date-picker/date-picker-story.ts, src/components/date-picker/date-picker.scss, src/components/dropdown/dropdown-story-react.tsx, src/components/toggle/toggle-story-angular.ts, src/components/toggle/toggle-story-react.tsx, src/components/toggle/toggle-story-vue.ts, src/components/toggle/toggle-story.ts, src/components/toggle/toggle.ts, tests/snapshots/bx-toggle.md, tests/spec/button_spec.ts, tests/spec/toggle_spec.ts
This change replaes misc boolean attributes with enum attribute. This ensures forward-compatibility in case additional color scheme option may be added.
=> chore(components): move by-state props to enums

src/components/date-picker/date-picker-input.ts, src/components/dropdown/dropdown.ts, src/components/input/input.ts, src/components/textarea/textarea.ts, src/globals/mixins/validity.ts, tests/spec/date-picker_spec.ts, tests/spec/dropdown_spec.ts, tests/spec/input_spec.ts, tests/spec/textarea_spec.ts
This change introduces a new mix-in that supports `checkValidity()` and `setCustomValidity()` APIs.
This is separate from the mix-in for `formdata` event, due to date picker. Date picker handles `formdata` event on `<bx-date-picker>`, but handles form validation on `<bx-date-picker-input>`, as the range mode has form validation UI both on start/end dates.
=> feat(components): form validation API support

src/components/data-table/table-toolbar-search.ts, src/components/dropdown/dropdown.ts, src/components/floating-menu/floating-menu.ts, src/components/modal/modal.ts, src/components/tabs/tabs.ts, src/components/ui-shell/header-menu.ts, src/globals/mixins/host-listener.ts
This change moves from `focus` to `focusin` and `blur` to `focusout`, given `focusin`/`focusout` events are supported by all browsers now.
This change also removes the code that allowed us to use event delegation technique with `focus`/`blur` events.
=> chore(components): use focusin/focusout events

package.json, yarn.lock
TypeScript 3.8 (commit `91ffa1c752ac26882b1426fb4c9012701c1d908e` in microsoft/TypeScript repo) seems to have removed `loadend` from `HTMLElementEventMap` that made our `.d.ts` files compiled with TypeScript 3.7 incompatible with TypeScript 3.8 applications.
This change upgrades our build toolchain to TypeScript 3.8 to address that problem. Our examples (notably Angular one) using TypeScript 3.7 doesn't seem to have been broken with such change.
Fixes #328.
=> chore(build): upgrade to TypeScript 3.8

src/components/date-picker/date-picker-input.ts, src/components/dropdown/dropdown.ts, src/components/input/input.ts, src/components/textarea/textarea.ts
This change fixes wrong `requiredValidityMessage` attribute names in various components, which should have been dash-cased.
=> fix(input): fix attribute name

src/components/date-picker/date-picker.ts
This change disables the mobile mode in `flatpickr` given such mode is hostile to our design.
Fixes #351.
=> fix(date-picker): disable mobile mode

package.json, src/components/floating-menu/floating-menu.ts, src/polyfills/index.ts
This change ensures `ResizeObserver` polyfill is not a hard-dependency, as `ResizeObserver` is supported in all modern browsers.
=> chore(dependencies): remove ResizeObserver

examples/codesandbox/form/redux-form/package.json, examples/codesandbox/react/package.json, gulp-tasks/build.js, gulpfile.js, package.json, tools/babel-plugin-create-react-custom-element-type-def.js, tools/babel-plugin-create-react-custom-element-type.js, yarn.lock
This change introduces a new Babel plugin to generate `.d.ts` for React wrapper components.
=> chore(react-wrapper): generate type definitions

src/components/progress-indicator/progress-indicator.scss
This change ensures the elements in shadow DOM catches up with change in the width of `<bx-progress-step>`.
Fixes #325.
=> chore(progress-indicator): flexible style for line

src/components/combo-box/combo-box-story-angular.ts, src/components/combo-box/combo-box-story-react.tsx, src/components/combo-box/combo-box-story-vue.ts, src/components/combo-box/combo-box-story.ts, src/components/combo-box/combo-box.scss, src/components/combo-box/combo-box.ts, src/components/dropdown/dropdown-item.ts, src/components/dropdown/dropdown-story-angular.ts, src/components/dropdown/dropdown-story-react.tsx, src/components/dropdown/dropdown-story-vue.ts, src/components/dropdown/dropdown-story.ts, src/components/dropdown/dropdown.scss, src/components/dropdown/dropdown.ts, src/components/multi-select/multi-select-story-angular.ts, src/components/multi-select/multi-select-story-react.tsx, src/components/multi-select/multi-select-story-vue.ts, src/components/multi-select/multi-select-story.ts, src/components/multi-select/multi-select.scss, src/components/multi-select/multi-select.ts
Introduces size variants for `<bx-combo-box>`, `<bx-dropdown>` and `<bx-multi-select>`, which are enabled by `size="sm"` or `size="xl"` attribute (and its corresponding property).
=> feat(dropdown): introduce size variants

src/components/combo-box/combo-box-story-angular.ts, src/components/combo-box/combo-box-story-react.tsx, src/components/combo-box/combo-box-story-vue.ts, src/components/combo-box/combo-box-story.ts, src/components/combo-box/combo-box.scss
Adds inline variant to `<bx-combo-box>`, which is enabled by `type="inline"` attribute and its corresponding property.
=> feat(combo-box): add inline variant

src/components/accordion/accordion-item.ts, src/components/data-table/table-batch-actions.ts, src/components/data-table/table-row.ts, src/components/notification/inline-notification.ts
Fixes the side effect of `delegatesFocus` shadow DOM property, similar or equal to [Chromium bug report number 950357](https://bugs.chromium.org/p/chromium/issues/detail?id=950357), where browser attempts to focus on the first focusable element if user clicks on a non-focusable element in shadow DOM.
Such behavior deprives user from the ability to select text in shadow DOM.
Fixes #363.
=> fix(components): make shadow DOM text selectable

src/components/accordion/accordion-item.ts, src/components/accordion/accordion.scss
This change introduces `<bx-accordion-item>` style responsive to the element width rather than viewport width.
Fixes #362.
=> feat(accordion): responsive upon container

src/globals/mixins/validity.ts
Changes [`_testValidity()` protected method in `ValidityMixin`](https://github.com/carbon-design-system/carbon-custom-elements/blob/v1.0.0-beta.12/src/globals/mixins/validity.ts#L22-L25), to support form validation status other than "required".
Also adds `_getValidityMessage()` protected method there so form-associated components can override the error messages associated with the status.
These allow form-associated components to do validations e.g. of the value is within the `min`/`max` range.
=> chore(validity): support multiple status

src/components/accordion/accordion-item.ts, src/components/tile/expandable-tile.ts, src/components/tile/tile-story-angular.ts, src/components/tile/tile-story-react.tsx, src/components/tile/tile-story-vue.ts, src/components/tile/tile-story.ts
This change lets screen reader announce the content associated with expando along with the ARIA state, instead of using assistive text like "Expand/Collapse". Doing so provides more natural announcement for screen reader users, as well as reduces the need for additional attributes for screen reader, allowing us to reduce the maintenance cost and allowing user to reduce translations.
=> chore(components): expando announcing content

src/globals/wrappers/createReactCustomElementType.ts, tests/spec/createReactCustomElementType_spec.ts, tools/babel-plugin-create-react-custom-element-type.js
This change adds support to React wrapper components for custom element properties that have no mapping to attribute.
=> feat(react-wrapper): support non-attribute props

src/components/floating-menu/floating-menu.ts
This change adds support for floating menus in modal by ensuring that floating menu body is in between `<bx-modal>`'s focus sentinels. Otherwise, an attempt to focus on floating menu body interferes with `<bx-modal>`' s focus-wrapping behavior that attemps moving focus back
in modal content.
=> fix(floating-menu): support for modal

src/components/modal/modal-story-angular.ts, src/components/modal/modal-story-react.tsx, src/components/modal/modal-story-vue.ts, src/components/modal/modal-story.ts
This change removes `danger` knob from `<bx-modal>` stories.
`<bx-modal>` has never supported `danger` attribute, as danger modal can be done by putting danger button into `<bx-modal-footer>`.
=> chore(devenv): remove danger knob

src/components/content-switcher/content-switcher-story-angular.ts, src/components/content-switcher/content-switcher-story-react.tsx, src/components/content-switcher/content-switcher-story-vue.ts, src/components/content-switcher/content-switcher-story.ts, src/components/tabs/tabs-story-angular.ts, src/components/tabs/tabs-story-react.tsx, src/components/tabs/tabs-story-vue.ts, src/components/tabs/tabs-story.ts
This change removes Storybook knobs for `disabled` property from `<bx-content-switcher>` and `<bx-tabs>`, because it was never supported.
Disabling can be done per-item level, i.e. `<bx-content-switcher-item>` and `<bx-tab>`.
=> chore(tabs): remove disabled knob

tools/check-license.js
This change fixes an issue in license checker code where files are being clobbered when one file is found as missing license header (completely) while another file is updating license year.
=> chore(lint): fix an error in check-license.js

src/components/input/input.ts, src/components/number-input/number-input-story.ts, src/components/number-input/number-input.ts, tests/snapshots/bx-number-input.md, tests/spec/number-input_spec.ts
This adds a number of tests for the number input component. A lot of the base tests are borrowed from `bx-input` with modifications.
=> chore(number-input): add tests

src/components/button/button.ts, src/components/link/link.ts, yarn.lock
This change makes `<bx-link>` code inheritable so we can support links with different contents seen in Carbon-derived design systems.
=> chore(link): make it inheritable

src/components/ui-shell/header-nav-item.ts, src/components/ui-shell/side-nav-link.ts, src/components/ui-shell/side-nav-menu-item.ts
This change adds `title` attribute support to several nav items in UI shell. `title` attribute works as text-only content of such nav items and it can be used instead of a child node.
=> feat(ui-shell): support title attribute

src/components/accordion/accordion.scss
We had a recent change in accordion style presumably to support multi-lines accordion title. However, the change made the text top-aligned for single line condition, and the CSS actually didn't support multi-lines accordion title. This change fixes those problems.
=> fix(accordion): make chevron center-aligned

src/components/modal/modal-close-button.ts, src/components/modal/modal.scss, tests/integration/ui/modal_steps.js
This change support keyboard action in `<bx-modal-close-button>` by wrapping it in a native `<button>`.
=> fix(modal): wrap close in native button

package.json
This adds the `"exports"` field as defined in Node.js 12 and 14 to enable subpath imports.
The current form is backwards compatible because the base-level files have been explicitly listed.
Ideally with the exports field, exact entry points would be listed, but the list here would be well over 100 which could be some work, but would have some benefits in hiding internal non public modules.
For now though, this will provide support to CDNs such as jspm and Skypack which use the "exports" field to determine how to resolve package subpaths. Specifically for jspm.dev this would ensure all subpaths are iterated and served, since usually subpaths are ignored as they might be tests etc.
Happy to answer any further questions around this, and the full docs on the field are available here - …
=> Expose package subpaths with the "exports" field

examples/codesandbox/ie/webpack.config.js, package.json, tests/integration/build/angular_steps.js, tests/integration/build/basic_steps.js, tests/integration/build/custom-style_steps.js, tests/integration/build/form-angular_steps.js, tests/integration/build/form-basic_steps.js, tests/integration/build/ie_steps.js, tests/integration/build/react_steps.js, tests/integration/build/redux-form_steps.js, tests/integration/build/rtl_steps.js, tests/integration/build/setup.js, tests/integration/build/theme-zoning_steps.js, tests/integration/build/vue_steps.js, tests/integration/replace-dependencies.js, yarn.lock
Changes test scripts for build integration tests so that the whole built package contents of `carbon-custom-elements` is used for build integration tests.
Before this change, only `es` directory used fresh package contents and the rest was from NPM, which means that changes in `package.json`, etc. were not tested.
This change also fixes broken build integration test of IE example, which was caused by a missing item in `exports` field.
=> test(integration): use full package

.storybook/webpack.config.js, gulp-tasks/config.js, gulp-tasks/test.js, package.json, tests/karma.conf.js, yarn.lock
This change replaces `sass-loader` in our Storybook environment with `fast-sass-loader` for better build speed.
=> chore(devenv): switch to fast-sass-loader

src/components/ui-shell/header-menu-button.ts, tests/snapshots/ui-shell.md
This change adds default label text for humberger menu button for side nav.
Refs carbon-design-system/ibm-dotcom-library#3161.
(Requires #446 to pass the CI)
=> fix(ui-shell): default label text

.storybook/basic-example-cdn.html, .storybook/preview-head.html, .storybook/webpack.config.js, README.md, docs/welcome-story.mdx, package.json, yarn.lock
This change adds a plain HTML example that works with a CDN supporting module mapping.
(Note: Requires #446 to pass the CI)
=> docs(readme): demo CDN example

src/globals/mixins/host-listener.ts
This change fixes an issue in `@HostListener()` decorator handling code where it gets broken if an event name with `-` is given.
=> fix(host-listener): support dash in event name

package.json
Newer version of `lint-staged` doesn't require `git add` in `.lintstagedrc`, and thus they are removed.
**Removed**
- `git add` in `.lintstagedrc`
=> chore(lint): update .lintstagedrc

src/components/notification/inline-notification.ts, src/components/notification/notification-story-angular.ts, src/components/notification/notification-story-react.tsx, src/components/notification/notification-story-vue.ts, src/components/notification/notification-story.ts, tests/spec/notification_spec.ts
Fix #291 
This changes add the property `timeout` to the components `inline-notification` and `toast-notification`. This new property will close the notification if a time (in ms) is specified after that time pass.
**New**
- New property `timeout` for: `inline-notification`, `toast-notification`.
No breaking changes.
=> feat(timeout): new property for the notification component

examples/codesandbox/basic/package.json, examples/codesandbox/form/basic/package.json, examples/codesandbox/form/redux-form/package.json, examples/codesandbox/react/package.json, examples/codesandbox/styling/custom-style/package.json, examples/codesandbox/styling/theme-zoning/package.json, src/components/ui-shell/side-nav.ts
Refs carbon-design-system/ibm-dotcom-library#3940.
This change ensures a side nav item is ready to be focused on before side nav sets focus on the first nav item when it's expanded.
**New**
- A mechanism to wait for `transitionend` event before `<bx-side-nav>` sets focus on the first nav item when it's expaneded.
=> fix(side-nav): focus on end-animation

README.md
**Changed**
- In top-level `README.md`, changes from `custom-elements.carbondesignsystem.com` to `web-components.carbondesignsystem.com`.
=> docs(readme): fix stale link

src/components/button/button-story.ts, src/components/button/button.ts
#534 
Adds tertiary and ghost variations to `danger` button.
**New**
- tertiary and ghost variations to `danger`
=> feat(button): add tertiary and ghost variants to danger

src/components/accordion/accordion-item.ts, src/components/accordion/accordion-story-angular.ts, src/components/accordion/accordion-story-react.tsx, src/components/accordion/accordion-story-vue.ts, src/components/accordion/accordion-story.ts, src/components/accordion/accordion.scss
#525 
Adds disabled state to accordion items.
**New**
- `disabled` state added to accordion items
**Changed**
- update CSS for disabled state when `open` is true
=> feat(accordion): add disabled state to accordion item

src/components/modal/modal-story.scss, src/components/modal/modal-story.ts
WebKit in the version of Playwright we are with seems to have a problem where `:host(bx-modal[open])` is defined before `:host(bx-modal)`.
This fixes the UI integration test failure caused by such problem.
**Changed**
- Workaround a problem in WebKit used in the Playwright version we are using that happens when 
`:host(bx-modal[open])` is defined before `:host(bx-modal)`.
=> test(integration-ui): fix for WebKit

README.md, examples/codesandbox/next/package.json, examples/codesandbox/react-ssr/package.json
Refs carbon-design-system/carbon-for-ibm-dotcom#4251.
Ensures React SSR and Next CodeSandbox examples run on Node `12.16.3`+ given CodeSandbox runs on older Node version by default.
**Changed**
- Ensures React SSR and Next CodeSandbox examples run on Node `12.16.3`+.
=> docs(examples): update React SSR

src/components/accordion/accordion-story-angular.ts, src/components/accordion/accordion-story-react.tsx, src/components/accordion/accordion-story-vue.ts, src/components/accordion/accordion-story.ts, src/components/accordion/accordion.scss, src/components/accordion/accordion.ts, src/components/accordion/defs.ts
#529 
This adds size variants to `accordion`.
**New**
- `sm` and `xl` sizes
=> feat(accordion): add size variants

src/components/overflow-menu/defs.ts, src/components/overflow-menu/overflow-menu-story-angular.ts, src/components/overflow-menu/overflow-menu-story-react.tsx, src/components/overflow-menu/overflow-menu-story-vue.ts, src/components/overflow-menu/overflow-menu-story.ts, src/components/overflow-menu/overflow-menu.scss, src/components/overflow-menu/overflow-menu.ts
#533 
This adds size variants to `overflow-menu`.
**New**
- `sm` and `xl` sizes
=> feat(overflow-menu): add size variants

src/components/content-switcher/content-switcher-story-angular.ts, src/components/content-switcher/content-switcher-story-react.tsx, src/components/content-switcher/content-switcher-story-vue.ts, src/components/content-switcher/content-switcher-story.ts, src/components/content-switcher/content-switcher.scss, src/components/content-switcher/content-switcher.ts, src/components/content-switcher/defs.ts
#528  
This adds size variants to `content-switcher`.
**New**
- `sm` and `xl` sizes
=> feat(content-switcher): add size variants

src/components/list/list.scss
This change works around a limitation in WebKit where `::before` pseudo element is not supported on `::slotted()` pseudo element.
Refs https://bugs.webkit.org/show_bug.cgi?id=178237.
Refs carbon-design-system/carbon-for-ibm-dotcom#4733.
**New**
- A workaround for a limitation in WebKit where `::before` pseudo element is not supported on `::slotted()` pseudo element.
=> fix(unordered-list): workaround for WebKit

src/components/ui-shell/side-nav.scss
Refs #564.
Fixes icon color in `<bx-side-nav-link>` by explicitly setting the color.
**Changed**
- A fix to icon color in `<bx-side-nav-link>`.
=> fix(side-nav): fix icon color

.github/workflows/deploy.yml
Ensures Angular storybook builds at last in the GH actions script to deploy the release to GH pages, given the Angular storybook build generates redundant `.d.ts` file that affects React storybook build.
**Changed**
- A change to ensure Angular storybook builds at last in the GH actions script to deploy the release to GH pages.
=> chore(build): change build order

tools/get-changelog.js
This is derived from a script we similarly use on Carbon for IBM.com,
where it can generate a prettified changelog based on conventional
commits. This is custom in that it breaks down based on the commit
types, either `features`, `fixes`, or `housekeeping`. It also groups the
subject names together into sub-bullets.
Example usage (from previous tag to HEAD):
`node ./tools/get-changelog.js -f v1.10.0`
Between two tags:
`node ./tools/get-changelog.js -f v1.0.0 -t v1.1.0`
This is what the output looks like currently if getting the changelog from the latest release tag:
- **content-switcher**
- add size variants (#561)
- **overflow-menu**
- add size variants (#560)
- **accordion**
- add size variants (#559)
- **side-nav**
- fix icon color (#565)
- **unordered-list**
- …
=> chore(changelog): adding script for generating changelogs

README.md, docs/welcome-story.mdx, tools/deploy.sh
Updates deploy script so that the GH pages doesn't use Jekyll.
**Changed**
- Deploy script so that the GH pages doesn't use Jekyll.
=> chore(ci): update deploy script

src/components/data-table/table-batch-actions.ts, src/components/data-table/table-toolbar-content.ts
#467
Tabbing now focuses on the action bar that is currently displayed. Before the change, continuous tabbing kept focusing on the bar that was hidden, which effectively 'hid' the proper bar from view.
**Changed**
- `tabIndex` toggles on each action bar depending on which one is being shown
=> fix(data-table): corrected tabbing into proper bars

src/components/file-uploader/file-uploader-story.mdx, src/components/file-uploader/file-uploader-story.ts, src/components/select/select-story.mdx, src/components/select/select-story.ts, src/components/skeleton-text/skeleton-text-story.ts
Refs #602.
Fixes JavaScript error in the Docs tab of the story of `<bx-skeleton-text>`. Also adds Docs tab code for
`<bx-file-uploader>` and `<bx-select>`.
**New**
- Docs tab code for `<bx-file-uploader>` and `<bx-select>`.
**Changed**
- Fixes JavaScript error in the Docs tab of the story of `<bx-skeleton-text>`.
=> chore(devenv): fix JS error in the Docs tab of skeleton text

src/index.ts
This PR adds `BXBreadcrumbItem` & `BXBreadcrumbLink` to exports. 
I'm not sure, maybe be these were intentionally left out? For my use case I am using snowpack and I can easily import other components, but was unable to import `BXBreadcrumbItem` & `BXBreadcrumbLink`.
**New** to `src/index.ts`
- `export { default as BXBreadcrumbItem } from './components/breadcrumb/breadcrumb-item';`
- `export { default as BXBreadcrumbLink } from './components/breadcrumb/breadcrumb-link';`
=> chore(export): add breadcrumb item and link

docs/welcome-story.mdx
This change is in response to the pull request to include documentation
on Carbon Web Components on the carbon design system website. This is to
clarify the differences between the pure framework libraries, and the
wrapper versions included with `carbon-web-components`.
**Changed**
- Welcome documentation
=> docs(welcome): updating content regarding framework wrappers

src/components/combo-box/combo-box.ts, tests/karma-setup-renderroot.js, tests/karma.conf.js, tests/spec/combo-box_spec.ts
Refs #620.
The X button in `<bx-combo-box>` used to merely clear the type-ahead field, which controls which `<bx-combo-box-item>` should be highlighted.
However, X button in the React version clears the selection as well. This change makes such behavior in sync with the React version.
The type-ahead field of `<bx-combo-box>` controls the highlight of `<bx-combo-box-item>`, not selection, and this change keeps such behavior intact. In other words, this change affect only the behavior of the X button.
**Changed**
- X button in `<bx-combo-box>` now clears the selection in addition to the highlight.
=> fix(combo-box): make X button clear the selection

README.md
Deploy previews have been moved to another solution, so removing Netlify
from the README.
**Changed**
- `README.md`
=> docs(readme): removing netlify from the README.md

src/components/ui-shell/header-menu.ts
https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/5650
Updating the chevron from the `header-menu` component to match the React version.
=> fix(header-menu): updating chevron to match react version

package.json
Noticed that the integration build tests are failing, which was also
something noticed in the `Carbon for IBM.com` repo around the same time,
and none of the recent code changes would indicate something that would
cause this. This is possibly an environment related issue (possible
latest Chrome version) that might be causing some rendering issues to
occur within these tests, but would need to dig more into this in a
separate PR.
**Changed**
- Removed `test:integration:build` from `ci-check` script
=> test(integration-build): temporarily suppressing test integration build

.github/workflows/publish.yml
This new action takes advantage of three different actions:
- npm-publish
- github-changelog-generator-action
- release-action
This will automatically publish if there is a new version of the package
on the master branch, then will 1) publish to NPM, 2) create a
changelog, then 3) create the Github release with the changelog.
**New**
- Github action for publishing to NPM and creation of github release
=> chore(publish): adding Github actions for automated publishing to NPM

package.json
This will release `v1.13.1` of `carbon-web-components`.
**Changed**
- `package.json`
=> chore(release): bumping to v1.13.1

.github/workflows/publish.yml
This changes out the github action used for generating the changelog to something that works. A test release was created on my fork:
https://github.com/jeffchew/carbon-web-components/releases/tag/v1.13.2
**Changed**
- publish.yml
=> fix(release): changing the changelog github action

package.json, src/components/modal/modal.scss
Restores `modal` open styles accidentally removed in #631.
**Changed**
- restore open styles for `modal`
=> fix(modal): fixes open styles

docs/form-story.mdx, src/components/dropdown/dropdown.ts
None.
`<bx-dropdown>` currently lacks FormData support that is seen in other component such as `<bx-input>`, meaning that the selected Dropdown value wouldn't get passed upon Form submission. This PR adds support for said feature.
**New**
- added support for `FormData` event in `<bx-dropdown>`
=> fix(dropdown): added formdata event support

src/components/select/select-story.mdx
None
The properties of `<bx-select-item>`'s were rendered twice by accident -- fixed it so `<bx-select>` properties render in the docs.
**New**
- showing `<bx-select>` properties in README
=> fix(select): show proper attributes in readme

src/components/data-table/_table-action.scss
#656 
The Carbon updates from a while ago made the Table Search component lose its expanded styles and animations. This PR restores those styles.
**New**
- added styles to ensure search bar opens
=> fix(table-search): ensures expanded search opens properly

src/components/search/search.ts
Web component: Dotcom shell - Locale modal- After giving the search input and activation of clear search input button the dialog is getting closed [#6078](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6078)
The Carbon for IBM.com Locale Modal extends the carbon-web-components `search` component. An accessibility issue was reported when search clear button is clicked, the focus doesn't return back to the input. This PR sets the focus back to input when clear input button is clicked.
The Carbon React and Angular instances of `search` have the same behavior where focus returns to input:
https://react.carbondesignsystem.com/?path=/story/components-search--default
https://angular.carbondesignsystem.com/?path=/story/components-search--basic
**Changed**
- set focus back to …
=> fix(search): set focus back to input when search is cleared

README.md
Refs #661 
This adds documentation for the main README on how to use in lieu of importing via ES modules.
**Changed**
- `README.md`
=> docs(cdn): adding documentation for CDN artifacts

.gitignore
This PR prevents macOS Finder autogenerated files from being tracked by git since it kept creeping into git diffs from just checking out the repo
**Changed**
- ignore `.DS_Store`
=> chore(gitignore): ignore `.DS_Store`

package.json
This will release `v1.16.1` of `carbon-web-components`.
**Changed**
- `package.json`
=> chore(release): bump version 1.16.1

package.json, src/components/ui-shell/header-menu.ts
Safari-only mega menu portion of https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6956
This PR restores `delegatesFocus` support for `header-menu` in Safari. This was originally disabled in https://github.com/carbon-design-system/carbon-web-components/pull/496 due to browser crashes, but the [original webkit bug appears to have been resolved](https://bugs.webkit.org/show_bug.cgi?id=215622).
I have scoped this PR to `header-menu` for now but I believe #496 may be reverted after further testing (so far have only tested header-menu, content-switcher-item and checkbox)
confirm that the issues fixed by #496 are not present in `BXHeaderMenu`
and confirm that the Cloud masthead is no longer showing the menu item click issue described in …
=> fix(header-menu): reenable shadow DOM `delegatesFocus` feature in Safari

.github/CODEOWNERS
This introduced a `CODEOWNERS` file so that pull requests can be automatically assigned.
**New**
- `CODEOWNERS`
=> chore(codeowners): adding codeowners file

src/components/radio-button/radio-button.ts, tests/snapshots/bx-radio-button.md
#695
This PR passes the value of the `disabled` prop to the shadow DOM `input` and also prevents `checked` from being applied if the input is already disabled
Confirm that a disabled radio input can no longer be manipulated
=> fix(radio-button): apply `disabled` prop to input

.github/workflows/deploy.yml, .github/workflows/publish.yml
This update will manually push up the new tag after a release, which should trigger the deploy workflow to run.
**Changed**
- Changes back to `push` in `deploy.yml`
- Add manual step to push the new tag after a publish is completed in `publish.yml`
=> fix(deploy): fix to properly tag the repo after publish

.github/workflows/percy-update-base.yml
Noticed that this job was no longer running. I believe that Ubuntu 16 was deprecated by Github, so need to update to use the latest Ubuntu instead.
**Changed**
- `percy-update-base.yml`
=> fix(github-actions): switched percy update to use ubuntu latest

.gitignore, README.md, package.json, yarn.lock
Refs https://github.com/carbon-design-system/carbon-web-components/issues/723
This moved the `lit-element`/`lit-html` libraries to core `dependencies`. `peerDependencies` was also cleaned up to no longer include `carbon-components`, as that has already been managed in `dependencies` for awhile now.
The scripts were also alphabetized in `package.json`, and added some additional entries to `.gitignore`.
**Changed**
- `lit-element`/`lit-html` moved to `dependencies`
- trimmed down `peerDependencies`
- Added `.npmrc` and `yarn-error.log` to `.gitignore`
- alphabetized scripts in `package.json`
- `README.md` updated to reflect installation changes
=> chore(lit): moved lit-element/lit-html to core dependencies

.github/workflows/ci-check.yml, .github/workflows/deploy.yml, .github/workflows/percy-update-base.yml, .github/workflows/publish.yml, .github/workflows/reviewdog.yml
Related with this update, the `setup-node` has a built-in option to cache:
https://github.com/actions/setup-node#caching-packages-dependencies
If you want to use it, I can add it in another PR.
**Changed**
- Update checkout and setup-node actions
=> chore: update checkout and setup-node actions

.github/workflows/ci-check.yml, .github/workflows/deploy.yml, .github/workflows/percy-update-base.yml, .github/workflows/publish.yml, .github/workflows/reviewdog.yml
As mention #729, just enabled the actions/setup-node@v2 built-in cache.
Let's see how improves the CI time.
=> chore: setup actions/setup-node@v2 cache

.github/workflows/dependabot-yarn-mirror.yml, .github/workflows/percy-update-base.yml
Noticed that the percy base wasn't getting updated, and saw that the rule added was causing this. This should re-enable percy base updating.
**Changed**
- `percy-update-base.yml` remove repo target check rule
=> fix(github-actions): turn back on percy update base

.github/workflows/percy-update-base.yml, .github/workflows/publish.yml
Sorry team, after some investigations we discovered that for on push actions there is no `pull_request` reference and the checks fail. This PR reverts the changes from my previous PR.
=> Revert "chore: make the forks check dynamic (#753)"

renovate.json
After observing other repo behavior, removing the separation of versions into separate PRs is probably better as it would start to generate too many PRs and would be a bit spammy. This will revert the config to closer to the default behavior.
**Changed**
- Removed `: separateMultipleMajorReleases`, and `:separatePatchReleases` default configs
=> chore(renovate): revert back to default renovate behavior

package.json
This bumps the library to v1.20.0.
**Changed**
- `package.json` bumped to version `1.20.0`
=> chore(release): bump to v1.20.0

src/components/file-uploader/file-uploader-item.ts
[Storybook]: Webcomponents File Upload Wrong Events Documentation #918
Storybook for `file-uploader` was not showing correct file uploader events. This PR corrects it.
BEFORE:
AFTER:
**Changed**
- fix documentation
=> docs(file-uploader): correct file uploader events documentation

.github/workflows/dependabot-yarn-mirror.yml, .github/workflows/publish.yml, package.json
This releases v1.21.0 of Carbon Web Components.
I have also snuck in a new workflow for updating the yarn offline mirror from dependabot, as well as a slight adjustment to the publish workflow to set the token on the checkout level.
**New**
- `dependabot-yarn-mirror.yml` for updating the offline mirror from dependabot PRs
**Changed**
- Bumped version to `v1.21.0` in `package.json`
- Set the github token in the `action/checkout` step in `publish.yml`
=> chore(release): bump to v1.21.0

.prettierignore, tools/deploy.sh
The `build-storybook:angular` script introduces a large amount of auto-generated DTS files. This removes them prior to running the `gh-pages` deploy script, which may be failing due to the inclusion of these files.
**New**
- remove untracked files added by `build-storybook:angular` script
- add `storybook-static*` directories to `prettierignore`
=> chore(ci): add git clean to remove angular artifacts

gulp-tasks/build/modules/css.js, gulp-tasks/test.js, package.json, tests/karma.conf.js, tests/utils/snapshot.js
#814 
This PR updates the karma config and gulp tasks to remove karma and autoprefixer warnings when running the test suite. It also adds an npm script for updating unit test snapshots to match our other repos
=> chore: remove deprecation warnings and add snapshot update script
